<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>home_additem11tocart</name>
   <tag></tag>
   <elementGuidId>27da37a0-5ec0-419f-9ad3-16abf12c723d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body > div.home-page.clearfix > div:nth-child(7) > div.row.add_ons_list > div:nth-child(7) > div.row > div > div:nth-child(3) > input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[3]/div[6]/div[2]/div[7]/div[2]/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_to_cart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to cart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control btn btn-default float-left button_add_to_cart</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;with_sticky_header&quot;]/div[@class=&quot;home-page clearfix&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row add_ons_list&quot;]/div[@class=&quot;col-sm-4 add_on_item&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 action_buttons&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control btn btn-default float-left button_add_to_cart&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='card_to_cart'])[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div[3]/input</value>
   </webElementXpaths>
</WebElementEntity>
